"""Added product table

Revision ID: 47480414ebc7
Revises: 
Create Date: 2025-03-20 16:38:46.404737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47480414ebc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('currencyId', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('vendor', sa.Text(), nullable=False),
    sa.Column('vendorCode', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('manufacturer_warranty', sa.Boolean(), nullable=False),
    sa.Column('pictures', sa.Text(), nullable=False),
    sa.Column('price_wholesale_rub', sa.Float(), nullable=False),
    sa.Column('bestseller', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('price_u_e', sa.Float(), nullable=False),
    sa.Column('quantity_in_stock_moscow_chashnikovo', sa.Text(), nullable=False),
    sa.Column('quantity_in_stock_moscow_kantemirovskaya', sa.Text(), nullable=False),
    sa.Column('quantity_in_stock_saint_petersburg', sa.Text(), nullable=False),
    sa.Column('quantity_in_stock_voronezh', sa.Text(), nullable=False),
    sa.Column('price_for_company_byn', sa.Float(), nullable=False),
    sa.Column('price_for_individual_byn', sa.Float(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('product_status', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
