"""New Products

Revision ID: 8fe99a9f0146
Revises: 
Create Date: 2025-04-09 21:54:32.194247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe99a9f0146'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=False),
    sa.Column('vendor_code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('warranty', sa.Boolean(), nullable=False),
    sa.Column('pictures', sa.Text(), nullable=False),
    sa.Column('wholesale_price', sa.Float(), nullable=False),
    sa.Column('bestseller', sa.Boolean(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('price_ue', sa.Float(), nullable=False),
    sa.Column('stock_moscow_chashnikovo', sa.String(), nullable=False),
    sa.Column('stock_moscow_kantemirovskaya', sa.Integer(), nullable=False),
    sa.Column('stock_spb', sa.Integer(), nullable=False),
    sa.Column('stock_voronezh', sa.Integer(), nullable=False),
    sa.Column('price_legal_by', sa.Float(), nullable=False),
    sa.Column('price_individual_by', sa.Float(), nullable=False),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('product_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_id')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
